<?xml version = "1.0" ?>
<robot name = "rover" xmlns:xacro = "http://www.ros.org/wiki/xacro">
    <!-- Colours -->
    <material name = "green">
        <color rgba = "0 0.6 0 1" />
    </material>
    <material name = "red">
        <color rgba = "0.6 0 0 1" />
    </material>
    <material name = "gray">
        <color rgba = "0.7 0.7 0.7 1" />
    </material>

    <!-- XACROS !!! -->
    <!-- Inertia Xacros -->
    <xacro:macro name = "box_inertia" params = "m x y z o_xyz o_rpy">
        <inertial>
            <mass value = "${m}"/>
            <origin xyz = "${o_xyz}" rpy = "${o_rpy}" />
            <inertia 
                ixx = "${(m / 12) * (z * z + y * y)}"
                iyy = "${(m / 12) * (x * x + z * z)}"
                izz = "${(m / 12) * (x * x + y * y)}"
                ixy = "0" iyz = "0" ixz = "0">
            </inertia>
        </inertial>
    </xacro:macro>
    <xacro:macro name = "cylinder_inertia" params = "m r l o_xyz o_rpy">
        <inertial>
            <mass value = "${m}"/>
            <origin xyz = "${o_xyz}" rpy = "${o_rpy}" />
            <inertia 
                ixx = "${(m / 12) * (3 * r * r + l * l)}"
                iyy = "${(m / 12) * (3 * r * r + l * l)}"
                izz = "${(m / 2) * (r * r)}"
                ixy = "0" iyz = "0" ixz = "0">
            </inertia>
        </inertial>
    </xacro:macro>
    <!-- May not be necessary ! -->
    <!-- <xacro:macro name = "sphere_inertia" params = "m r o_xyz o_rpy">
        <inertial>
            <mass value = "${m}"/>
            <origin xyz = "${o_xyz}" rpy = "${o_rpy}" />
            <inertia 
                ixx = "${(2 / 5) * m * r * r}"
                iyy = "${(2 / 5) * m * r * r}"
                izz = "${(2 / 5) * m * r * r}"
                ixy = "0" iyz = "0" ixz = "0">
            </inertia>
        </inertial>
    </xacro:macro> -->
    <xacro:macro name = "wheel_link" params = "prefix">
        <link name = "${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius = "${wheel_radius}" length = "${wheel_length}" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "${pi / 2.0} 0 0" />
                <material name = "gray" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius = "${wheel_radius}" />
                </geometry>
                <origin xyz = "0 0 0" rpy = "0 0 0" />
            </collision>
            <xacro:cylinder_inertia m = "${wheel_mass}" r = "${wheel_radius}" l = "${wheel_length}" o_xyz = "0 0 0" o_rpy = "${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>
    <xacro:macro name = "wheel_joint" params = "prefix x y">
        <joint name = "base_${prefix}_wheel_joint" type = "continuous">
            <parent link = "base_link" />
            <child link = "${prefix}_wheel_link" />
            <origin xyz = "${x} ${y} 0" rpy = "0 0 0" />
            <axis xyz = "0 1 0" />
        </joint>
    </xacro:macro>

    <!-- Properties -->
    <xacro:property name = "base_length" value = "0.8" />
    <xacro:property name = "base_width" value = "0.6" />
    <xacro:property name = "base_height" value = "0.2" />
    <xacro:property name = "wheel_radius" value = "0.1" />
    <xacro:property name = "wheel_length" value = "0.05" />
    <xacro:property name = "wheel_mass" value = "1.0"/>
    <xacro:property name = "box_mass" value = "5.0"/>

    <!-- TF Tree starts here -->
    <link name = "base_footprint" />
    <link name = "base_link">
        <visual>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
            <material name = "red" />
        </visual>
        <collision>
            <geometry>
                <box size = "${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz = "0 0 ${base_height / 2.0}" rpy = "0 0 0" />
        </collision>
        <xacro:box_inertia m = "${box_mass}" x="${base_length}" y="${base_width}" z="${base_height}" o_xyz="0 0 ${base_height / 2.0}" o_rpy="0 0 0" />
    </link>
    <xacro:wheel_link prefix = "front_right" />
    <xacro:wheel_link prefix = "front_left" />
    <xacro:wheel_link prefix = "back_right" />
    <xacro:wheel_link prefix = "back_left" />
    <joint name = "base_joint" type = "fixed">
        <parent link = "base_footprint" />
        <child link = "base_link" />
        <origin xyz = "0 0 ${wheel_radius}" rpy = "0 0 0" />
    </joint>
    <xacro:wheel_joint prefix = "front_right" x = "${base_length / 4.0}" y = "${-(base_width + wheel_length) / 2.0}" />
    <xacro:wheel_joint prefix = "front_left" x = "${base_length / 4.0}" y = "${(base_width + wheel_length) / 2.0}" />
    <xacro:wheel_joint prefix = "back_right" x = "${-base_length / 4.0}" y = "${-(base_width + wheel_length) / 2.0}" />
    <xacro:wheel_joint prefix = "back_left" x = "${-base_length / 4.0}" y = "${(base_width + wheel_length) / 2.0}" />
</robot>